# Excluir las migraciones del cálculo de cobertura de pruebas
sonar.coverage.exclusions=src/modules/**/migrations/*.ts

# Excluir las migraciones del análisis de duplicación de código
sonar.cpd.exclusions=src/modules/**/migrations/*.ts